[package]
name = "locational_codes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
morton = { git = "https://github.com/SRaimondi/morton.git", branch = "master"}